title: 'Christophior'
description: 'Hi. I''m Chris Villarreal, a PayPal Software Engineer from Austin, Texas!'
meta_description: 'Personal site of Herald Chris Villarreal, University of Texas Alumnus and PayPal Software Engineer from Austin, Texas.'

markdown: redcarpet
highlighter: pygments